sudo: false
language: java

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.gradle

script:
  - ./gradlew
  - git clone https://github.com/huxi/lilith.git ~/builds/lilith 
  - pushd ~/builds/lilith
  - ./gradlew install 
  - popd 

env:
- TERM=dumb

after_success:
- ./gradlew cleanTest
- ./gradlew jacocoRootReport
- ./gradlew coveralls
